name: Selenium Tests

on:
  schedule:
    - cron: '0 3,11,17 * * *'  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager pandas

      # - name: Run CIE June 2019 tests
      #   run: pytest test_CIEJune2019Markscheme.py   --tb=short --junitxml=results.xml

      - name: Run CIE Specimen 2020 tests
        run: pytest test_CIESpecimen2020Markscheme.py   --tb=short --junitxml=results.xml

            
      # Upload screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png


      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.csv
